"""
💎 V21.1 APEX QUANTUM PRIME: INSTITUTIONAL RISK VAULT
------------------------------------------------------------
Features:
- Discrete Binary Kelly Criterion (f* = p - q/b) using empirical R-multiples
- L-Moment Generalized Pareto Distribution (GPD) Heavy-Tail Risk Estimator
- Margin & Heat Map Allocation Caps
- Exact NaN/Inf Sanitization & Matrix Invertibility Guards
"""

import math
import logging
from typing import Dict, List, Any, Optional, Tuple
from collections import deque
import numpy as np
import pandas as pd

logger = logging.getLogger("QUANT_CORE.RISK_VAULT")


class InstitutionalRiskVault:
    def __init__(
        self, 
        max_drawdown_pct: float = 0.30, 
        max_single_position_risk_pct: float = 0.05, 
        exchange_min_notional: float = 6.50
    ):
        self.max_drawdown_pct = max_drawdown_pct
        self.max_single_position_risk_pct = max_single_position_risk_pct
        self.exchange_min_notional = exchange_min_notional
        
        self.absolute_max_leverage: float = 5.0
        self.base_leverage: float = 3.0
        
        self.peak_balance = 0.0
        self.current_drawdown_state = 0.0
        self.emergency_circuit_breaker = False
        
        self.active_positions: Dict[str, float] = {}
        self.correlation_matrix: Optional[pd.DataFrame] = None

        self.outcomes_history = deque(maxlen=2000) 
        self.avg_win_r = 1.5   
        self.avg_loss_r = 1.0  
        self.volatility_surface: deque = deque(maxlen=300)

    def push_microstructure_variance(self, variance: float):
        if variance > 0 and not math.isnan(variance) and not math.isinf(variance):
            self.volatility_surface.append(variance)

    def calculate_evt_tail_risk(self) -> float:
        """
        🚀 V21.0 ROBUST L-MOMENT EVT (PEAKS-OVER-THRESHOLD)
        Replaces the fragile Hill Estimator. Uses L-Moments to fit the Generalized 
        Pareto Distribution (GPD), which is mathematically immune to small-sample 
        variance explosions and never requires matrix inversion.
        """
        if len(self.volatility_surface) < 50:
            return 1.0  
            
        try:
            vol_arr = np.array(self.volatility_surface, dtype=float)
            vol_arr = np.sort(vol_arr[~np.isnan(vol_arr)])
            
            if len(vol_arr) == 0:
                return 1.0
                
            # 90th percentile threshold (u)
            k = max(5, int(len(vol_arr) * 0.10))
            threshold = vol_arr[-k]
            
            # Extract exceedances above the threshold
            exceedances = vol_arr[-k:] - threshold
            
            if threshold <= 0 or len(exceedances) < 3:
                return 1.0
                
            # 🚀 L-Moments method for GPD (Highly robust)
            # l_1 = mean, l_2 = half mean mean difference
            l_1 = np.mean(exceedances)
            n = len(exceedances)
            
            # Vectorized L-2 moment computation
            j = np.arange(1, n + 1)
            l_2 = np.sum(exceedances * ((2 * j - 1 - n) / (n * (n - 1))))
            
            # GPD Tail Index (Xi)
            if l_2 == 0: 
                return 1.0
                
            tau = l_2 / l_1
            xi = 2.0 - (1.0 / tau)
            
            # Sizing Penalty Application: Compress sizing if tail index is heavy (xi > 0.15)
            if xi > 0.15:
                # Huber-style clipping to prevent absolute position eradication
                tail_penalty = min(0.65, (xi - 0.15) * 2.5)
                return max(0.35, 1.0 - tail_penalty)
                
            return 1.05 # Reward tight, well-behaved tails with a slight leverage bump
            
        except Exception as e:
            logger.debug(f"[MATH_WARN] L-Moment GPD EVT calculation fallback: {e}")
            return 1.0

    def update_correlation_matrix(self, price_histories: Dict[str, List[float]]):
        try:
            if not price_histories:
                return
                
            min_len = min([len(prices) for prices in price_histories.values()])
            if min_len < 30: 
                return
            
            trimmed_histories = {sym: prices[-min_len:] for sym, prices in price_histories.items()}
            df = pd.DataFrame(trimmed_histories, dtype=float)
            
            # Log diffs with safe zero-division avoidance
            shifted = df.shift(1)
            returns_df = np.log(df / shifted.replace(0, np.nan)).dropna()
            
            # Fill NaNs generated by zero-variance series to prevent propagation
            self.correlation_matrix = returns_df.corr().fillna(0.0)
            logger.info("[X-RAY] 🧠 Risk Parity Matrix Updated: Full pairwise correlation computed.")
        except Exception as e:
            logger.debug(f"[MATH_WARN] Failed to compute correlation matrix: {e}")

    def update_kelly_metrics(self, is_win: bool, realized_r_multiple: float):
        if math.isnan(realized_r_multiple) or math.isinf(realized_r_multiple):
            return
            
        self.outcomes_history.append(1.0 if is_win else 0.0)
        
        if is_win:
            capped_r = min(5.0, max(0.1, abs(realized_r_multiple)))
            self.avg_win_r = (self.avg_win_r * 0.95) + (capped_r * 0.05)
        else:
            capped_r = min(2.5, max(0.1, abs(realized_r_multiple)))
            self.avg_loss_r = (self.avg_loss_r * 0.95) + (capped_r * 0.05)

    def get_dynamic_conviction_threshold(self, balance: float, net_edge_bps: float = 50.0) -> float:
        """
        Sets a flat 51.8% base conviction floor for micro-accounts.
        """
        if math.isnan(balance) or math.isinf(balance):
            balance = 12.0
            
        base_threshold = 0.518
        # High Net Expected Value (EV) Discount (up to 1.0% discount for sharp edges)
        ev_discount = min(0.010, max(0.0, (net_edge_bps - 40.0) / 5000.0))
        
        return max(0.508, base_threshold - ev_discount)

    def get_max_allowed_slots(self, balance: float) -> int:
        """Universal Max of 5."""
        return 5

    def calculate_optimal_fraction(self, base_confidence: float, net_edge_bps: float = 50.0, current_balance: float = 100.0, symbol_variance: float = 1e-4) -> float:
        """
        🚀 V21.1 BINARY KELLY CRITERION
        Replaces the dimensionally flawed Continuous Merton-Kelly with a robust 
        Discrete Binary Kelly (f* = (p*b - q) / b) utilizing historical R-multiples.
        """
        # 1. Micro-Calibrated EV Conviction Check
        min_required_conviction = self.get_dynamic_conviction_threshold(current_balance, net_edge_bps)
        if base_confidence < min_required_conviction:
            return 0.0  # Rejected by Dynamic EV Gate

        # 2. Discrete Binary Kelly Sizing
        p = base_confidence
        q = 1.0 - p
        
        # Calculate empirical payoff ratio (b)
        b = self.avg_win_r / max(self.avg_loss_r, 1e-9)
        
        if b <= 0:
            return 0.001
            
        # Binary Kelly Fraction
        raw_kelly = p - (q / b)
        
        # Block negative edge sizings
        if raw_kelly <= 0.0:
            return 0.0
        
        # 3. Half-Kelly for safety + L-Moment EVT Tail Penalty + Drawdown Penalty
        half_kelly = raw_kelly / 2.0
        evt_multiplier = self.calculate_evt_tail_risk()
        drawdown_penalty = max(0.10, 1.0 - (self.current_drawdown_state * 3.0))
        
        risk_adjusted_kelly = half_kelly * evt_multiplier * drawdown_penalty
        
        if math.isnan(risk_adjusted_kelly) or math.isinf(risk_adjusted_kelly):
            return 0.001
            
        return max(0.001, min(self.max_single_position_risk_pct, risk_adjusted_kelly))

    def evaluate_portfolio_safety(self, current_balance: float, new_position_notional: float = 0.0, symbol: str = "") -> Tuple[bool, str]:
        if self.emergency_circuit_breaker:
            return False, "EMERGENCY_CIRCUIT_BREAKER_ACTIVE"

        if math.isnan(current_balance) or math.isinf(current_balance):
            return False, "INVALID_BALANCE_STATE"

        if current_balance > self.peak_balance:
            self.peak_balance = current_balance
            self.current_drawdown_state = 0.0
        elif self.peak_balance > 0:
            self.current_drawdown_state = (self.peak_balance - current_balance) / self.peak_balance
            
            if self.current_drawdown_state >= self.max_drawdown_pct:
                if not self.emergency_circuit_breaker:
                    logger.critical(f"🚨 ABSOLUTE MAX DRAWDOWN BREACHED ({self.current_drawdown_state:.2%}). LOCKING DOWN SYSTEMS.")
                    self.emergency_circuit_breaker = True
                return False, f"MAX_DRAWDOWN_BREACHED_{self.current_drawdown_state:.2%}"

        if symbol in self.active_positions:
            return False, f"DUPLICATE_SYMBOL_LOCK ({symbol})"

        max_slots = self.get_max_allowed_slots(current_balance)
        if len(self.active_positions) >= max_slots:
            return False, f"DYNAMIC_SLOT_CAP_REACHED // Active: {len(self.active_positions)} >= Max Allowed: {max_slots}"

        evt_multiplier = self.calculate_evt_tail_risk()
        dynamic_corr_threshold = max(0.40, min(0.85, 0.85 * evt_multiplier - (self.current_drawdown_state * 1.5)))

        if symbol and new_position_notional > 0:
            if hasattr(self, 'correlation_matrix') and self.correlation_matrix is not None:
                for active_sym in self.active_positions.keys():
                    if active_sym in self.correlation_matrix.index and symbol in self.correlation_matrix.columns:
                        corr_value = float(self.correlation_matrix.loc[active_sym, symbol])
                        if not math.isnan(corr_value) and corr_value > dynamic_corr_threshold:
                            return False, f"RISK_PARITY_BLOCK // {symbol} correlates {corr_value:.2f} with {active_sym} (Max allowed: {dynamic_corr_threshold:.2f})"

        # NATURAL HEAT MAP (Organic Scaling)
        # Allows an organic 1.8x leveraged equity multiplier to efficiently use available margin
        max_heat_dollars = max(self.exchange_min_notional * 2.5, current_balance * 1.8)
        total_exposure = sum(self.active_positions.values()) + new_position_notional

        if total_exposure > max_heat_dollars:
            return False, f"NATURAL_HEAT_CAP_EXCEEDED // Req: ${total_exposure:.2f} > Max Margin Available: ${max_heat_dollars:.2f}"
                
        return True, "SAFE"

    def update_position_ledger(self, symbol: str, notional_value: float):
        if notional_value <= 0 or math.isnan(notional_value) or math.isinf(notional_value):
            self.active_positions.pop(symbol, None)
        else:
            self.active_positions[symbol] = notional_value

    def clear_ledger(self):
        self.active_positions.clear()