"""
💎 V15.1 APEX OMEGA: INSTITUTIONAL RISK VAULT
------------------------------------------------------------
Features:
- Beta-Binomial Bayesian Conjugate Kelly Sizing (2,000 Trade Memory)[cite: 1]
- Peaks-Over-Threshold (POT) Heavy-Tail EVT Risk Estimator[cite: 1]
- Margin & Heat Map Allocation Caps[cite: 1]
- Exact NaN/Inf Sanitization & Matrix Invertibility Guards[cite: 1]
"""

import math
import logging
from typing import Dict, List, Any, Optional, Tuple
from collections import deque
import numpy as np
import pandas as pd

logger = logging.getLogger("QUANT_CORE.RISK_VAULT")


class InstitutionalRiskVault:
    def __init__(
        self, 
        max_drawdown_pct: float = 0.30, 
        max_single_position_risk_pct: float = 0.015,
        exchange_min_notional: float = 6.50
    ):
        self.max_drawdown_pct = max_drawdown_pct
        self.max_single_position_risk_pct = max_single_position_risk_pct
        self.exchange_min_notional = exchange_min_notional
        
        self.absolute_max_leverage: float = 5.0
        self.base_leverage: float = 3.0
        
        self.peak_balance = 0.0
        self.current_drawdown_state = 0.0
        self.emergency_circuit_breaker = False
        
        self.active_positions: Dict[str, float] = {}
        self.correlation_matrix: Optional[pd.DataFrame] = None

        # Expanded memory to 2000 to prevent Kelly Sample Starvation[cite: 1]
        self.outcomes_history = deque(maxlen=2000) 
        self.avg_win_r = 1.5   
        self.avg_loss_r = 1.0  
        self.volatility_surface: deque = deque(maxlen=300)

    def push_microstructure_variance(self, variance: float):
        if variance > 0 and not math.isnan(variance) and not math.isinf(variance):
            self.volatility_surface.append(variance)

    def calculate_evt_tail_risk(self) -> float:
        """
        PEAKS-OVER-THRESHOLD (POT) EVT ESTIMATOR[cite: 1]
        Estimates the Pareto tail index (xi) using the Hill estimator on variance exceedances.[cite: 1]
        """
        if len(self.volatility_surface) < 50:
            return 1.0  
            
        try:
            vol_arr = np.sort(np.array(self.volatility_surface, dtype=float))
            
            # Prevent NaN/Inf arrays from crashing the calculation[cite: 1]
            if np.isnan(vol_arr).any() or np.isinf(vol_arr).any():
                return 1.0
                
            # 90th percentile threshold (u)
            k = max(5, int(len(vol_arr) * 0.10))
            threshold = vol_arr[-k]
            tail_data = vol_arr[-k:]
            
            if threshold <= 0 or len(tail_data) == 0:
                return 1.0
                
            # Hill Estimator for Heavy Tails: xi = (1/k) * sum(log(X_i / u))[cite: 1]
            xi = float(np.mean(np.log(tail_data / (threshold + 1e-9))))
            
            # If tail index is heavy (xi > 0.20), scale down sizing proportionally[cite: 1]
            if xi > 0.20:
                tail_penalty = min(0.60, (xi - 0.20) * 3.0)
                return max(0.40, 1.0 - tail_penalty)
                
            return 1.05
        except Exception as e:
            logger.debug(f"[MATH_WARN] Numerical instability in POT-EVT calculation: {e}")
            return 1.0

    def update_correlation_matrix(self, price_histories: Dict[str, List[float]]):
        try:
            if not price_histories:
                return
                
            min_len = min([len(prices) for prices in price_histories.values()])
            if min_len < 30: 
                return
            
            trimmed_histories = {sym: prices[-min_len:] for sym, prices in price_histories.items()}
            df = pd.DataFrame(trimmed_histories, dtype=float)
            
            # Log diffs with safe zero-division avoidance[cite: 1]
            shifted = df.shift(1)
            returns_df = np.log(df / shifted.replace(0, np.nan)).dropna()
            
            # Fill NaNs generated by zero-variance series to prevent propagation[cite: 1]
            self.correlation_matrix = returns_df.corr().fillna(0.0)
            logger.info("[X-RAY] 🧠 Risk Parity Matrix Updated: Full pairwise correlation computed.")
        except Exception as e:
            logger.debug(f"[MATH_WARN] Failed to compute correlation matrix: {e}")

    def update_kelly_metrics(self, is_win: bool, realized_r_multiple: float):
        if math.isnan(realized_r_multiple) or math.isinf(realized_r_multiple):
            return
            
        self.outcomes_history.append(1.0 if is_win else 0.0)
        
        if is_win:
            capped_r = min(5.0, max(0.1, abs(realized_r_multiple)))
            self.avg_win_r = (self.avg_win_r * 0.95) + (capped_r * 0.05)
        else:
            capped_r = min(2.5, max(0.1, abs(realized_r_multiple)))
            self.avg_loss_r = (self.avg_loss_r * 0.95) + (capped_r * 0.05)

    def get_dynamic_conviction_threshold(self, balance: float, net_edge_bps: float = 50.0) -> float:
        """
        MICRO-CALIBRATED CONVICTION THRESHOLD[cite: 1]
        Sets a flat 51.8% base conviction floor for micro-accounts.[cite: 1]
        """
        if math.isnan(balance) or math.isinf(balance):
            balance = 12.0
            
        base_threshold = 0.518
        # High Net Expected Value (EV) Discount (up to 1.0% discount for sharp edges)[cite: 1]
        ev_discount = min(0.010, max(0.0, (net_edge_bps - 40.0) / 5000.0))
        
        return max(0.508, base_threshold - ev_discount)

    def get_max_allowed_slots(self, balance: float) -> int:
        """Universal Max of 5[cite: 1]."""
        return 5

    def calculate_optimal_fraction(self, base_confidence: float, net_edge_bps: float = 50.0, current_balance: float = 100.0) -> float:
        """
        BAYESIAN CONJUGATE KELLY SIZING[cite: 1]
        """
        # 1. Micro-Calibrated EV Conviction Check[cite: 1]
        min_required_conviction = self.get_dynamic_conviction_threshold(current_balance, net_edge_bps)
        if base_confidence < min_required_conviction:
            return 0.0  # Rejected by Dynamic EV Gate[cite: 1]

        # 2. Beta-Binomial Bayesian Sizing[cite: 1]
        # Beta(12, 10) Skeptical Conjugate Prior (~54.5% baseline)[cite: 1]
        alpha_prior = 12.0
        beta_prior = 10.0
        wins = sum(self.outcomes_history)
        total = len(self.outcomes_history)
        
        p_bayesian = (wins + alpha_prior) / (total + alpha_prior + beta_prior)
        b = self.avg_win_r / (self.avg_loss_r + 1e-9)
        
        if b <= 0:
            raw_kelly = 0.001
        else:
            kf = (p_bayesian * b - (1.0 - p_bayesian)) / b
            if kf <= 0 or math.isnan(kf):
                return 0.0
            raw_kelly = kf / 2.0  # Half-Kelly for margin of safety[cite: 1]
        
        evt_multiplier = self.calculate_evt_tail_risk()
        edge_factor = min(1.5, max(0.5, net_edge_bps / 50.0))
        drawdown_penalty = max(0.10, 1.0 - (self.current_drawdown_state * 3.0))
        
        risk_adjusted_kelly = raw_kelly * evt_multiplier * edge_factor * drawdown_penalty
        
        if math.isnan(risk_adjusted_kelly) or math.isinf(risk_adjusted_kelly):
            return 0.001
            
        return max(0.001, min(self.max_single_position_risk_pct, risk_adjusted_kelly))

    def evaluate_portfolio_safety(self, current_balance: float, new_position_notional: float = 0.0, symbol: str = "") -> Tuple[bool, str]:
        if self.emergency_circuit_breaker:
            return False, "EMERGENCY_CIRCUIT_BREAKER_ACTIVE"

        if math.isnan(current_balance) or math.isinf(current_balance):
            return False, "INVALID_BALANCE_STATE"

        if current_balance > self.peak_balance:
            self.peak_balance = current_balance
            self.current_drawdown_state = 0.0
        elif self.peak_balance > 0:
            self.current_drawdown_state = (self.peak_balance - current_balance) / self.peak_balance
            
            if self.current_drawdown_state >= self.max_drawdown_pct:
                if not self.emergency_circuit_breaker:
                    logger.critical(f"🚨 ABSOLUTE MAX DRAWDOWN BREACHED ({self.current_drawdown_state:.2%}). LOCKING DOWN SYSTEMS.")
                    self.emergency_circuit_breaker = True
                return False, f"MAX_DRAWDOWN_BREACHED_{self.current_drawdown_state:.2%}"

        if symbol in self.active_positions:
            return False, f"DUPLICATE_SYMBOL_LOCK ({symbol})"

        max_slots = self.get_max_allowed_slots(current_balance)
        if len(self.active_positions) >= max_slots:
            return False, f"DYNAMIC_SLOT_CAP_REACHED // Active: {len(self.active_positions)} >= Max Allowed: {max_slots}"

        evt_multiplier = self.calculate_evt_tail_risk()
        dynamic_corr_threshold = max(0.40, min(0.85, 0.85 * evt_multiplier - (self.current_drawdown_state * 1.5)))

        if symbol and new_position_notional > 0:
            if hasattr(self, 'correlation_matrix') and self.correlation_matrix is not None:
                for active_sym in self.active_positions.keys():
                    if active_sym in self.correlation_matrix.index and symbol in self.correlation_matrix.columns:
                        corr_value = float(self.correlation_matrix.loc[active_sym, symbol])
                        if not math.isnan(corr_value) and corr_value > dynamic_corr_threshold:
                            return False, f"RISK_PARITY_BLOCK // {symbol} correlates {corr_value:.2f} with {active_sym} (Max allowed: {dynamic_corr_threshold:.2f})"

        # Natural Heat Map (Organic Scaling)[cite: 1]
        # Allows an organic 1.8x leveraged equity multiplier to efficiently use available margin[cite: 1]
        max_heat_dollars = max(self.exchange_min_notional * 2.5, current_balance * 1.8)
        total_exposure = sum(self.active_positions.values()) + new_position_notional

        if total_exposure > max_heat_dollars:
            return False, f"NATURAL_HEAT_CAP_EXCEEDED // Req: ${total_exposure:.2f} > Max Margin Available: ${max_heat_dollars:.2f}"
                
        return True, "SAFE"

    def update_position_ledger(self, symbol: str, notional_value: float):
        if notional_value <= 0 or math.isnan(notional_value) or math.isinf(notional_value):
            self.active_positions.pop(symbol, None)
        else:
            self.active_positions[symbol] = notional_value

    def clear_ledger(self):
        self.active_positions.clear()